# Generated by Django 5.1 on 2026-05-24 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatedStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_type", models.CharField(max_length=50)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("day", "Last 24 Hours"),
                            ("week", "Last 7 Days"),
                            ("month", "Last 30 Days"),
                        ],
                        max_length=10,
                    ),
                ),
                ("avg_value", models.FloatField(default=0)),
                ("min_value", models.FloatField(default=0)),
                ("max_value", models.FloatField(default=0)),
                ("count", models.IntegerField(default=0)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregated_stats",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
                "unique_together": {("device", "metric_type", "period")},
            },
        ),
        migrations.CreateModel(
            name="DeviceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        help_text="Type of metric: temperature, humidity, power, etc.",
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "metric_type", "-timestamp"],
                        name="telemetry_d_device__d330eb_idx",
                    )
                ],
            },
        ),
    ]
